# fly.toml app configuration file generated for moulton on 2023-08-12T01:20:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "moulton"
primary_region = "mad"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
